[app]
url = "localhost:8080"
swagger = "http://localhost:58810"

[datasource]
host = "localhost"
port = "5432"
user = "otus_user"
password = "dev_pass"
db-name = "antibforce"
ssl = "disable"
migrations-dir = "migrations"